trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'azureacr'
    repository: 'juice-shop'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

